const DEFAULT_HYDERABAD_COORD = { latitude: 17.4065, longitude: 78.4772 };

const AREA_COORDS = {
  Abids: { latitude: 17.3898, longitude: 78.4766 },
  AdarshNagar: { latitude: 17.4062, longitude: 78.4691 },
  Aghapura: { latitude: 17.3846, longitude: 78.4617 },
  Ameerpet: { latitude: 17.4375, longitude: 78.4483 },
  Attapur: { latitude: 17.3685, longitude: 78.4292 },
  Bachupally: { latitude: 17.5449, longitude: 78.3677 },
  Balanagar: { latitude: 17.4754, longitude: 78.4482 },
  BandlagudaJagir: { latitude: 17.3461, longitude: 78.3927 },
  BanjaraHills: { latitude: 17.4126, longitude: 78.4483 },
  Basheerbagh: { latitude: 17.4012, longitude: 78.4774 },
  Begumpet: { latitude: 17.4374, longitude: 78.4569 },
  BegumBazaar: { latitude: 17.3753, longitude: 78.4752 },
  Bowenpally: { latitude: 17.4639, longitude: 78.4835 },
  Chaderghat: { latitude: 17.3748, longitude: 78.4931 },
  ChandaNagar: { latitude: 17.4939, longitude: 78.3317 },
  Charminar: { latitude: 17.3616, longitude: 78.4747 },
  Chikkadpally: { latitude: 17.4046, longitude: 78.4963 },
  Dilsukhnagar: { latitude: 17.3688, longitude: 78.5247 },
  ECIL: { latitude: 17.4697, longitude: 78.5717 },
  Erragadda: { latitude: 17.4532, longitude: 78.4334 },
  Falaknuma: { latitude: 17.3305, longitude: 78.4672 },
  FilmNagar: { latitude: 17.4234, longitude: 78.4058 },
  FinancialDistrict: { latitude: 17.4147, longitude: 78.3441 },
  Gachibowli: { latitude: 17.4401, longitude: 78.3489 },
  Gandipet: { latitude: 17.3919, longitude: 78.3187 },
  Ghatkesar: { latitude: 17.4508, longitude: 78.6854 },
  Golconda: { latitude: 17.3833, longitude: 78.4011 },
  Hafeezpet: { latitude: 17.4842, longitude: 78.3593 },
  Hayathnagar: { latitude: 17.3289, longitude: 78.6033 },
  Himayatnagar: { latitude: 17.4007, longitude: 78.4896 },
  HITECcity: { latitude: 17.4474, longitude: 78.3762 },
  Habsiguda: { latitude: 17.4154, longitude: 78.5436 },
  JubileeHills: { latitude: 17.4326, longitude: 78.4071 },
  Kachiguda: { latitude: 17.3898, longitude: 78.4989 },
  Karkhana: { latitude: 17.4594, longitude: 78.5059 },
  Khairatabad: { latitude: 17.412, longitude: 78.4621 },
  Kokapet: { latitude: 17.3948, longitude: 78.3322 },
  Kompally: { latitude: 17.5366, longitude: 78.4854 },
  Kondapur: { latitude: 17.4647, longitude: 78.3666 },
  Koti: { latitude: 17.385, longitude: 78.4867 },
  Kukatpally: { latitude: 17.4933, longitude: 78.3998 },
  LBnagar: { latitude: 17.3457, longitude: 78.5522 },
  Lakdikapul: { latitude: 17.404, longitude: 78.4629 },
  LangarHouz: { latitude: 17.3784, longitude: 78.4255 },
  Madhapur: { latitude: 17.4483, longitude: 78.3915 },
  Malakpet: { latitude: 17.3735, longitude: 78.5034 },
  Manikonda: { latitude: 17.403, longitude: 78.3774 },
  MasabTank: { latitude: 17.4014, longitude: 78.4531 },
  Mehdipatnam: { latitude: 17.3957, longitude: 78.4428 },
  Miyapur: { latitude: 17.493, longitude: 78.3918 },
  Moosapet: { latitude: 17.4663, longitude: 78.4251 },
  Malkajgiri: { latitude: 17.4474, longitude: 78.5351 },
  Musheerabad: { latitude: 17.4156, longitude: 78.4989 },
  Nallagandla: { latitude: 17.4751, longitude: 78.3072 },
  Nampally: { latitude: 17.3925, longitude: 78.4704 },
  Nanakramguda: { latitude: 17.4118, longitude: 78.3428 },
  Narayanguda: { latitude: 17.3978, longitude: 78.4905 },
  Nizampet: { latitude: 17.5187, longitude: 78.3827 },
  OldCity: { latitude: 17.3616, longitude: 78.4747 },
  OsmanSagar: { latitude: 17.3815, longitude: 78.2989 },
  Patancheru: { latitude: 17.5334, longitude: 78.2645 },
  Punjagutta: { latitude: 17.4264, longitude: 78.4516 },
  Raidurg: { latitude: 17.441, longitude: 78.3772 },
  RajendraNagar: { latitude: 17.3198, longitude: 78.4036 },
  Ramnagar: { latitude: 17.4096, longitude: 78.5111 },
  Sainikpuri: { latitude: 17.4899, longitude: 78.5491 },
  SanathNagar: { latitude: 17.4561, longitude: 78.4433 },
  Secunderabad: { latitude: 17.4337, longitude: 78.5016 },
  Shamshabad: { latitude: 17.2403, longitude: 78.4294 },
  Shaikpet: { latitude: 17.4012, longitude: 78.3941 },
  Somajiguda: { latitude: 17.4241, longitude: 78.4585 },
  SRnagar: { latitude: 17.4415, longitude: 78.4451 },
  Tarnaka: { latitude: 17.4287, longitude: 78.5419 },
  Tolichowki: { latitude: 17.3984, longitude: 78.4136 },
  Uppal: { latitude: 17.4016, longitude: 78.5603 },
  Vanasthalipuram: { latitude: 17.329, longitude: 78.5752 },
  Yousufguda: { latitude: 17.4353, longitude: 78.4268 }
};

const CATEGORY_ICONS = {
  Address: "map-marker-radius",
  Airport: "airport",
  Area: "map-marker-radius",
  Bus: "bus",
  Campus: "school",
  Hospital: "hospital-building",
  Hotel: "bed",
  Landmark: "map-marker-radius",
  Mall: "shopping",
  Market: "store",
  Metro: "subway-variant",
  Office: "office-building",
  Park: "tree",
  Railway: "train",
  Temple: "map-marker-radius"
};

function makeId(title, area) {
  return `${title}-${area}`
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function place({ title, area, areaKey, category = "Area", subtitle, icon, latitude, longitude, tags = [] }) {
  const coordinate = latitude && longitude
    ? { latitude, longitude }
    : AREA_COORDS[areaKey] || DEFAULT_HYDERABAD_COORD;

  return {
    id: makeId(title, area),
    title,
    subtitle: subtitle || `${area}, Hyderabad`,
    area,
    category,
    icon: icon || CATEGORY_ICONS[category] || "map-marker-radius",
    coordinate,
    tags: Array.from(new Set([
      title,
      area,
      category,
      subtitle || "",
      ...tags
    ].filter(Boolean).map((tag) => String(tag).toLowerCase())))
  };
}

const AREA_PLACES = [
  ["Abids", "Abids"],
  ["Adarsh Nagar", "AdarshNagar"],
  ["Afzalgunj", "Koti"],
  ["Aghapura", "Aghapura"],
  ["Ameerpet", "Ameerpet"],
  ["Amberpet", "Chaderghat"],
  ["Attapur", "Attapur"],
  ["Bachupally", "Bachupally"],
  ["Bahadurpura", "OldCity"],
  ["Balanagar", "Balanagar"],
  ["Bandlaguda Jagir", "BandlagudaJagir"],
  ["Banjara Hills", "BanjaraHills"],
  ["Basheerbagh", "Basheerbagh"],
  ["Begumpet", "Begumpet"],
  ["Begum Bazaar", "BegumBazaar"],
  ["BHEL Township", "Patancheru"],
  ["Boduppal", "Uppal"],
  ["Bolarum", "Secunderabad"],
  ["Bowenpally", "Bowenpally"],
  ["Chaderghat", "Chaderghat"],
  ["Chanda Nagar", "ChandaNagar"],
  ["Chandrayangutta", "OldCity"],
  ["Chikkadpally", "Chikkadpally"],
  ["Dilsukhnagar", "Dilsukhnagar"],
  ["Domalguda", "Himayatnagar"],
  ["ECIL", "ECIL"],
  ["Erragadda", "Erragadda"],
  ["Falaknuma", "Falaknuma"],
  ["Film Nagar", "FilmNagar"],
  ["Financial District", "FinancialDistrict"],
  ["Gachibowli", "Gachibowli"],
  ["Gandipet", "Gandipet"],
  ["Ghatkesar", "Ghatkesar"],
  ["Golconda", "Golconda"],
  ["Habsiguda", "Habsiguda"],
  ["Hafeezpet", "Hafeezpet"],
  ["Hayathnagar", "Hayathnagar"],
  ["Himayatnagar", "Himayatnagar"],
  ["HITEC City", "HITECcity", ["hitech city", "cyberabad"]],
  ["Hyderguda", "Basheerbagh"],
  ["Jubilee Hills", "JubileeHills"],
  ["Kachiguda", "Kachiguda", ["kacheguda"]],
  ["Karkhana", "Karkhana"],
  ["Khairatabad", "Khairatabad"],
  ["Kokapet", "Kokapet"],
  ["Kompally", "Kompally"],
  ["Kondapur", "Kondapur"],
  ["Koti", "Koti"],
  ["KPHB Colony", "Kukatpally", ["kukatpally housing board", "kphb"]],
  ["Kukatpally", "Kukatpally"],
  ["L.B Nagar", "LBnagar", ["lb nagar", "l b nagar"]],
  ["Lakdikapul", "Lakdikapul"],
  ["Langar Houz", "LangarHouz"],
  ["Madhapur", "Madhapur"],
  ["Malakpet", "Malakpet"],
  ["Malkajgiri", "Malkajgiri"],
  ["Manikonda", "Manikonda"],
  ["Masab Tank", "MasabTank"],
  ["Mehdipatnam", "Mehdipatnam"],
  ["Miyapur", "Miyapur"],
  ["Moosapet", "Moosapet"],
  ["Musheerabad", "Musheerabad"],
  ["Nacharam", "Habsiguda"],
  ["Nallagandla", "Nallagandla"],
  ["Nampally", "Nampally"],
  ["Nanakramguda", "Nanakramguda"],
  ["Narayanguda", "Narayanguda"],
  ["Narsingi", "Kokapet"],
  ["Nizampet", "Nizampet"],
  ["Old City", "OldCity"],
  ["Osman Nagar", "Nallagandla"],
  ["Patancheru", "Patancheru"],
  ["Pragathi Nagar", "Nizampet"],
  ["Punjagutta", "Punjagutta", ["panjagutta"]],
  ["Raidurg", "Raidurg", ["raidurgam"]],
  ["Rajendra Nagar", "RajendraNagar"],
  ["Ramnagar", "Ramnagar", ["ram nagar"]],
  ["Sainikpuri", "Sainikpuri"],
  ["Sanath Nagar", "SanathNagar"],
  ["Secunderabad", "Secunderabad"],
  ["Serilingampally", "Nallagandla"],
  ["Shamshabad", "Shamshabad"],
  ["Shaikpet", "Shaikpet"],
  ["Somajiguda", "Somajiguda"],
  ["S.R Nagar", "SRnagar", ["sr nagar", "s r nagar"]],
  ["Tarnaka", "Tarnaka"],
  ["Tolichowki", "Tolichowki", ["towlichowki"]],
  ["Uppal", "Uppal"],
  ["Vanasthalipuram", "Vanasthalipuram"],
  ["Yousufguda", "Yousufguda"]
].map(([title, areaKey, tags]) => place({ title, area: title, areaKey, category: "Area", tags: tags || [] }));

const TRANSIT_PLACES = [
  place({ title: "Rajiv Gandhi International Airport", area: "Shamshabad", areaKey: "Shamshabad", category: "Airport", subtitle: "Airport Road, Shamshabad", tags: ["rgia", "hyderabad airport", "departures", "arrivals", "flight"] }),
  place({ title: "GMR AeroCity Hyderabad", area: "Shamshabad", areaKey: "Shamshabad", category: "Airport", subtitle: "Near Rajiv Gandhi International Airport", tags: ["aerocity", "airport hotel"] }),
  place({ title: "Kacheguda Railway Station", area: "Kachiguda", areaKey: "Kachiguda", category: "Railway", subtitle: "Kachiguda, Hyderabad", tags: ["kacheguda", "kachiguda", "train"] }),
  place({ title: "Secunderabad Railway Station", area: "Secunderabad", areaKey: "Secunderabad", category: "Railway", subtitle: "Regimental Bazaar, Secunderabad", tags: ["train", "railway"] }),
  place({ title: "Hyderabad Deccan Railway Station", area: "Nampally", areaKey: "Nampally", category: "Railway", subtitle: "Nampally, Hyderabad", tags: ["nampally station", "railway", "train"] }),
  place({ title: "Begumpet Railway Station", area: "Begumpet", areaKey: "Begumpet", category: "Railway", tags: ["train", "railway"] }),
  place({ title: "Lingampalli Railway Station", area: "Serilingampally", areaKey: "Nallagandla", category: "Railway", tags: ["lingampally", "railway", "train"] }),
  place({ title: "Hafeezpet Railway Station", area: "Hafeezpet", areaKey: "Hafeezpet", category: "Railway", tags: ["railway", "train"] }),
  place({ title: "HITEC City MMTS Station", area: "HITEC City", areaKey: "HITECcity", category: "Railway", tags: ["mmts", "train", "hitech"] }),
  place({ title: "Malkajgiri Railway Station", area: "Malkajgiri", areaKey: "Malkajgiri", category: "Railway", tags: ["train", "railway"] }),
  place({ title: "Mahatma Gandhi Bus Station", area: "Afzalgunj", areaKey: "Koti", category: "Bus", subtitle: "MGBS, Imlibun", tags: ["mgbs", "bus stand", "imlibun"] }),
  place({ title: "Jubilee Bus Station", area: "Secunderabad", areaKey: "Secunderabad", category: "Bus", subtitle: "JBS, Parade Ground", tags: ["jbs", "bus stand", "parade ground"] }),
  place({ title: "Kukatpally Bus Stop", area: "Kukatpally", areaKey: "Kukatpally", category: "Bus", tags: ["kphb", "bus stop"] }),
  place({ title: "Uppal Bus Stand", area: "Uppal", areaKey: "Uppal", category: "Bus", tags: ["bus stand"] }),
  place({ title: "Mehdipatnam Bus Stop", area: "Mehdipatnam", areaKey: "Mehdipatnam", category: "Bus", tags: ["bus stop"] }),
  place({ title: "Aramghar Bus Stop", area: "Rajendra Nagar", areaKey: "RajendraNagar", category: "Bus", tags: ["aramghar", "bus stop"] }),
  place({ title: "Koti Bus Stop", area: "Koti", areaKey: "Koti", category: "Bus", tags: ["bus stop"] }),
  place({ title: "Secunderabad Clock Tower Bus Stop", area: "Secunderabad", areaKey: "Secunderabad", category: "Bus", tags: ["clock tower", "bus stop"] })
];

const METRO_STATIONS = [
  ["Miyapur Metro Station", "Miyapur"],
  ["JNTU College Metro Station", "Kukatpally", ["jntu"]],
  ["KPHB Colony Metro Station", "Kukatpally", ["kphb"]],
  ["Kukatpally Metro Station", "Kukatpally"],
  ["Balanagar Metro Station", "Balanagar"],
  ["Moosapet Metro Station", "Moosapet"],
  ["Bharat Nagar Metro Station", "Moosapet"],
  ["Erragadda Metro Station", "Erragadda"],
  ["ESI Hospital Metro Station", "SRnagar", ["esi"]],
  ["S.R Nagar Metro Station", "SRnagar", ["sr nagar"]],
  ["Ameerpet Metro Station", "Ameerpet"],
  ["Punjagutta Metro Station", "Punjagutta", ["panjagutta"]],
  ["Irrum Manzil Metro Station", "Khairatabad"],
  ["Khairatabad Metro Station", "Khairatabad"],
  ["Lakdikapul Metro Station", "Lakdikapul"],
  ["Assembly Metro Station", "Nampally"],
  ["Nampally Metro Station", "Nampally"],
  ["Gandhi Bhavan Metro Station", "Nampally"],
  ["Osmania Medical College Metro Station", "Koti"],
  ["MG Bus Station Metro Station", "Koti", ["mgbs"]],
  ["Malakpet Metro Station", "Malakpet"],
  ["New Market Metro Station", "Malakpet"],
  ["Musarambagh Metro Station", "Dilsukhnagar"],
  ["Dilsukhnagar Metro Station", "Dilsukhnagar"],
  ["Chaitanyapuri Metro Station", "Dilsukhnagar"],
  ["Victoria Memorial Metro Station", "LBnagar"],
  ["L.B Nagar Metro Station", "LBnagar", ["lb nagar"]],
  ["Nagole Metro Station", "Uppal"],
  ["Uppal Metro Station", "Uppal"],
  ["Stadium Metro Station", "Habsiguda"],
  ["NGRI Metro Station", "Habsiguda"],
  ["Habsiguda Metro Station", "Habsiguda"],
  ["Tarnaka Metro Station", "Tarnaka"],
  ["Mettuguda Metro Station", "Tarnaka"],
  ["Secunderabad East Metro Station", "Secunderabad"],
  ["Parade Ground Metro Station", "Secunderabad"],
  ["Paradise Metro Station", "Secunderabad"],
  ["Rasoolpura Metro Station", "Begumpet"],
  ["Prakash Nagar Metro Station", "Begumpet"],
  ["Begumpet Metro Station", "Begumpet"],
  ["Madhura Nagar Metro Station", "Yousufguda"],
  ["Yousufguda Metro Station", "Yousufguda"],
  ["Jubilee Hills Road No. 5 Metro Station", "JubileeHills"],
  ["Jubilee Hills Check Post Metro Station", "JubileeHills"],
  ["Peddamma Temple Metro Station", "JubileeHills"],
  ["Madhapur Metro Station", "Madhapur"],
  ["Durgam Cheruvu Metro Station", "Madhapur"],
  ["HITEC City Metro Station", "HITECcity", ["hitech city"]],
  ["Raidurg Metro Station", "Raidurg", ["raidurgam"]],
  ["JBS Parade Ground Metro Station", "Secunderabad", ["jbs"]],
  ["Secunderabad West Metro Station", "Secunderabad"],
  ["Gandhi Hospital Metro Station", "Musheerabad"],
  ["Musheerabad Metro Station", "Musheerabad"],
  ["RTC Cross Roads Metro Station", "Chikkadpally", ["rtc x roads"]],
  ["Chikkadpally Metro Station", "Chikkadpally"],
  ["Narayanaguda Metro Station", "Narayanguda"],
  ["Sultan Bazaar Metro Station", "Koti"]
].map(([title, areaKey, tags]) => place({ title, area: title.replace(" Metro Station", ""), areaKey, category: "Metro", tags: tags || [] }));

const LANDMARKS = [
  ["Charminar", "Charminar", "Charminar Road, Old City", ["old city", "laad bazaar"]],
  ["Golconda Fort", "Golconda", "Ibrahim Bagh, Hyderabad", ["fort"]],
  ["Tank Bund", "Khairatabad", "Hussain Sagar Lake Road", ["hussain sagar"]],
  ["Necklace Road", "Khairatabad", "Hussain Sagar Lake Road", ["hussain sagar"]],
  ["Hussain Sagar", "Khairatabad", "Tank Bund, Hyderabad", ["lake", "buddha statue"]],
  ["Birla Mandir", "AdarshNagar", "Hill Fort Road", ["temple"]],
  ["Salar Jung Museum", "OldCity", "Darulshifa, Hyderabad", ["museum"]],
  ["Chowmahalla Palace", "OldCity", "Khilwat, Hyderabad", ["palace"]],
  ["Qutb Shahi Tombs", "Golconda", "Ibrahim Bagh, Hyderabad", ["tombs"]],
  ["Nehru Zoological Park", "RajendraNagar", "Bahadurpura, Hyderabad", ["zoo"]],
  ["Lumbini Park", "Khairatabad", "Near Hussain Sagar", ["park"]],
  ["NTR Gardens", "Khairatabad", "Central Hyderabad", ["park"]],
  ["KBR National Park", "JubileeHills", "Jubilee Hills, Hyderabad", ["park", "kasu brahmananda reddy"]],
  ["Durgam Cheruvu", "Madhapur", "Madhapur, Hyderabad", ["lake", "cable bridge"]],
  ["Durgam Cheruvu Cable Bridge", "Madhapur", "Madhapur, Hyderabad", ["bridge", "cable bridge"]],
  ["Shilparamam", "HITECcity", "HITEC City, Hyderabad", ["craft village"]],
  ["Public Gardens", "Nampally", "Nampally, Hyderabad", ["bagh e aam", "park"]],
  ["Ravindra Bharathi", "Lakdikapul", "Saifabad, Hyderabad", ["auditorium"]],
  ["Prasads Multiplex", "Khairatabad", "Necklace Road, Hyderabad", ["imax", "cinema"]],
  ["Jalavihar Water Park", "Khairatabad", "Necklace Road, Hyderabad", ["water park"]],
  ["Snow World", "AdarshNagar", "Lower Tank Bund", ["theme park"]],
  ["Ramoji Film City", "Hayathnagar", "Abdullapurmet, Hyderabad", ["film city"]],
  ["Wonderla Hyderabad", "Shamshabad", "Raviryala, Hyderabad", ["theme park"]],
  ["Statue of Equality", "Shamshabad", "Muchintal, Hyderabad", ["ramanuja"]],
  ["Taramati Baradari", "Golconda", "Ibrahim Bagh, Hyderabad", ["heritage"]]
].map(([title, areaKey, subtitle, tags]) => place({ title, area: subtitle.split(",")[0], areaKey, category: "Landmark", subtitle, tags }));

const HOSPITALS = [
  ["Apollo Hospitals Jubilee Hills", "JubileeHills", "Road No. 72, Jubilee Hills"],
  ["KIMS Hospitals Secunderabad", "Secunderabad", "Minister Road, Secunderabad"],
  ["Yashoda Hospitals Somajiguda", "Somajiguda", "Raj Bhavan Road, Somajiguda"],
  ["Yashoda Hospitals Secunderabad", "Secunderabad", "Alexander Road, Secunderabad"],
  ["Yashoda Hospitals Hitec City", "HITECcity", "HITEC City, Hyderabad"],
  ["AIG Hospitals Gachibowli", "Gachibowli", "Gachibowli, Hyderabad"],
  ["CARE Hospitals Banjara Hills", "BanjaraHills", "Road No. 1, Banjara Hills"],
  ["CARE Hospitals HITEC City", "HITECcity", "HITEC City, Hyderabad"],
  ["Continental Hospitals", "Gachibowli", "Financial District, Hyderabad"],
  ["Sunshine Hospitals Secunderabad", "Secunderabad", "Paradise Circle, Secunderabad"],
  ["Rainbow Children's Hospital Banjara Hills", "BanjaraHills", "Road No. 10, Banjara Hills"],
  ["Rainbow Children's Hospital Kondapur", "Kondapur", "Kondapur, Hyderabad"],
  ["Basavatarakam Indo American Cancer Hospital", "BanjaraHills", "Road No. 10, Banjara Hills"],
  ["NIMS Hospital", "Punjagutta", "Punjagutta, Hyderabad"],
  ["Osmania General Hospital", "Koti", "Afzalgunj, Hyderabad"],
  ["Gandhi Hospital", "Secunderabad", "Musheerabad, Hyderabad"],
  ["LV Prasad Eye Institute", "BanjaraHills", "Road No. 2, Banjara Hills"],
  ["Malla Reddy Narayana Hospital", "Kompally", "Suraram, Hyderabad"],
  ["Kamineni Hospitals LB Nagar", "LBnagar", "L.B Nagar, Hyderabad"],
  ["Medicover Hospitals HITEC City", "HITECcity", "HITEC City, Hyderabad"],
  ["Citizens Specialty Hospital", "Nallagandla", "Nallagandla, Hyderabad"]
].map(([title, areaKey, subtitle]) => place({ title, area: subtitle.split(",")[0], areaKey, category: "Hospital", subtitle, tags: ["hospital", "medical"] }));

const SHOPPING_AND_MARKETS = [
  ["Inorbit Mall Cyberabad", "Madhapur", "Madhapur, Hyderabad", "Mall"],
  ["Sarath City Capital Mall", "Kondapur", "Kondapur, Hyderabad", "Mall"],
  ["Forum Sujana Mall", "Kukatpally", "Kukatpally, Hyderabad", "Mall"],
  ["GVK One Mall", "BanjaraHills", "Road No. 1, Banjara Hills", "Mall"],
  ["Next Galleria Mall Punjagutta", "Punjagutta", "Punjagutta, Hyderabad", "Mall"],
  ["Next Galleria Mall Irrum Manzil", "Khairatabad", "Irrum Manzil, Hyderabad", "Mall"],
  ["Manjeera Mall", "Kukatpally", "Kukatpally, Hyderabad", "Mall"],
  ["Hyderabad Central Mall", "Punjagutta", "Punjagutta, Hyderabad", "Mall"],
  ["IKEA Hyderabad", "Raidurg", "Raidurg, Hyderabad", "Market"],
  ["Begum Bazaar", "BegumBazaar", "Goshamahal, Hyderabad", "Market"],
  ["Laad Bazaar", "Charminar", "Charminar, Hyderabad", "Market"],
  ["Sultan Bazaar", "Koti", "Koti, Hyderabad", "Market"],
  ["Koti Book Market", "Koti", "Koti, Hyderabad", "Market"],
  ["General Bazaar", "Secunderabad", "Secunderabad, Hyderabad", "Market"],
  ["Monda Market", "Secunderabad", "Secunderabad, Hyderabad", "Market"],
  ["Shilparamam Night Bazaar", "HITECcity", "HITEC City, Hyderabad", "Market"],
  ["Abids Shopping Street", "Abids", "Abids, Hyderabad", "Market"],
  ["Charminar Market", "Charminar", "Old City, Hyderabad", "Market"],
  ["Kukatpally Shopping Area", "Kukatpally", "Kukatpally, Hyderabad", "Market"],
  ["Ameerpet Shopping Area", "Ameerpet", "Ameerpet, Hyderabad", "Market"]
].map(([title, areaKey, subtitle, category]) => place({ title, area: subtitle.split(",")[0], areaKey, category, subtitle, tags: ["shopping"] }));

const OFFICES_AND_CAMPUSES = [
  ["T-Hub", "Raidurg", "Raidurg, Hyderabad", "Office", ["startup"]],
  ["Cyber Towers", "HITECcity", "HITEC City, Hyderabad", "Office", ["hitech city"]],
  ["Mindspace Madhapur", "Madhapur", "HITEC City, Hyderabad", "Office", ["raheja mindspace"]],
  ["DLF Cyber City Hyderabad", "Gachibowli", "Gachibowli, Hyderabad", "Office", ["dlf"]],
  ["Raheja Mindspace IT Park", "Madhapur", "Madhapur, Hyderabad", "Office", ["mindspace"]],
  ["Divyasree Orion SEZ", "Raidurg", "Raidurg, Hyderabad", "Office", ["orion"]],
  ["Knowledge City Hyderabad", "Raidurg", "Raidurg, Hyderabad", "Office", ["knowledge city"]],
  ["Waverock SEZ", "FinancialDistrict", "Financial District, Hyderabad", "Office", ["wave rock"]],
  ["Amazon HYD13", "FinancialDistrict", "Financial District, Hyderabad", "Office", ["amazon"]],
  ["Microsoft India Development Center", "Gachibowli", "Gachibowli, Hyderabad", "Office", ["microsoft"]],
  ["Google Hyderabad Office", "HITECcity", "HITEC City, Hyderabad", "Office", ["google"]],
  ["Infosys Pocharam Campus", "Ghatkesar", "Pocharam, Hyderabad", "Office", ["infosys"]],
  ["Wipro Gachibowli Campus", "Gachibowli", "Gachibowli, Hyderabad", "Office", ["wipro"]],
  ["IIT Hyderabad City Office", "Kandi", "Hyderabad Region", "Campus", ["iit"]],
  ["Indian School of Business", "Gachibowli", "Gachibowli, Hyderabad", "Campus", ["isb"]],
  ["University of Hyderabad", "Gachibowli", "Gachibowli, Hyderabad", "Campus", ["uoh"]],
  ["IIIT Hyderabad", "Gachibowli", "Gachibowli, Hyderabad", "Campus", ["iiit"]],
  ["Osmania University", "Tarnaka", "Tarnaka, Hyderabad", "Campus", ["ou"]],
  ["JNTU Hyderabad", "Kukatpally", "Kukatpally, Hyderabad", "Campus", ["jntu"]],
  ["NALSAR University of Law", "Shamirpet", "Hyderabad Region", "Campus", ["nalsar"]],
  ["BITS Pilani Hyderabad Campus", "Shamirpet", "Hyderabad Region", "Campus", ["bits"]],
  ["CBIT Hyderabad", "Gandipet", "Gandipet, Hyderabad", "Campus", ["cbit"]],
  ["MGIT Hyderabad", "Gandipet", "Gandipet, Hyderabad", "Campus", ["mgit"]],
  ["Gokaraju Rangaraju Institute", "Bachupally", "Bachupally, Hyderabad", "Campus", ["grriet"]]
].map(([title, areaKey, subtitle, category, tags]) => place({ title, area: subtitle.split(",")[0], areaKey, category, subtitle, tags }));

const HOTELS_TEMPLES_PARKS = [
  ["Taj Krishna", "BanjaraHills", "Road No. 1, Banjara Hills", "Hotel"],
  ["Taj Deccan", "BanjaraHills", "Banjara Hills, Hyderabad", "Hotel"],
  ["ITC Kohenur", "Madhapur", "Madhapur, Hyderabad", "Hotel"],
  ["The Westin Hyderabad Mindspace", "Madhapur", "Mindspace, Madhapur", "Hotel"],
  ["Novotel Hyderabad Convention Centre", "HITECcity", "HITEC City, Hyderabad", "Hotel"],
  ["Park Hyatt Hyderabad", "BanjaraHills", "Road No. 2, Banjara Hills", "Hotel"],
  ["Falaknuma Palace", "Falaknuma", "Falaknuma, Hyderabad", "Hotel"],
  ["Peddamma Temple", "JubileeHills", "Jubilee Hills, Hyderabad", "Temple"],
  ["Chilkur Balaji Temple", "Gandipet", "Chilkur, Hyderabad", "Temple"],
  ["Jagannath Temple Hyderabad", "BanjaraHills", "Road No. 12, Banjara Hills", "Temple"],
  ["Ujjaini Mahakali Temple", "Secunderabad", "Secunderabad, Hyderabad", "Temple"],
  ["Sanghi Temple", "Hayathnagar", "Hyderabad Region", "Temple"],
  ["Botanical Garden Kondapur", "Kondapur", "Kondapur, Hyderabad", "Park"],
  ["Indira Park", "AdarshNagar", "Lower Tank Bund, Hyderabad", "Park"],
  ["Sanjeevaiah Park", "Khairatabad", "Hussain Sagar, Hyderabad", "Park"],
  ["Mrugavani National Park", "Gandipet", "Chilkur, Hyderabad", "Park"]
].map(([title, areaKey, subtitle, category]) => place({ title, area: subtitle.split(",")[0], areaKey, category, subtitle }));

const RECENT_ADDRESS_PLACES = [
  place({ title: "Nimboliadda", area: "Kachiguda", areaKey: "Kachiguda", category: "Address", subtitle: "Kachiguda, Hyderabad, Telangana 500027, India", latitude: 17.3868, longitude: 78.4939, tags: ["nimboliadda", "nimboli adda", "kachiguda"] }),
  place({ title: "Charlapalli", area: "Secunderabad", areaKey: "Secunderabad", category: "Address", subtitle: "Secunderabad, Telangana, India", latitude: 17.4686, longitude: 78.6016, tags: ["charlapalli", "cherlapally", "cherlapalli"] }),
  place({ title: "Karmanghat Hanuman Temple", area: "Champapet", areaKey: "LBnagar", category: "Temple", subtitle: "Inner Ring Road, Virat Nagar, Champapet, Telangana", latitude: 17.3412, longitude: 78.5318, tags: ["karmanghat", "hanuman temple", "champapet", "inner ring road"] }),
  place({ title: "Gayatri Nilayam", area: "Gaddiannaram", areaKey: "Dilsukhnagar", category: "Address", subtitle: "9-72, Gayatri Nilayam, Gaddiannaram, Vijeta Super Market Road", latitude: 17.3668, longitude: 78.5264, tags: ["gayatri nilayam", "gaddiannaram", "vijeta"] }),
  place({ title: "Konark Towers", area: "New Malakpet", areaKey: "Malakpet", category: "Address", subtitle: "New Malakpet, Hyderabad, Telangana 500036", latitude: 17.3752, longitude: 78.5108, tags: ["konark towers", "new malakpet"] }),
  place({ title: "87", area: "Kachiguda", areaKey: "Kachiguda", category: "Address", subtitle: "near Shivalayam Sri Sringeri Sharadha Chandramouleshwara Temple", latitude: 17.3898, longitude: 78.4989, tags: ["87", "shivalayam", "sringeri", "sharadha", "chandramouleshwara"] }),
  place({ title: "17-391/5/472", area: "Kalyan Nagar", areaKey: "LBnagar", category: "Address", subtitle: "Sai Ganga Colony, Shankeshwar Bazar, Kalyan Nagar", latitude: 17.3457, longitude: 78.5522, tags: ["17-391", "17 391", "sai ganga colony", "shankeshwar bazar", "kalyan nagar"] })
];

const COMMON_ADDRESSES = [
  place({ title: "Road No. 1, Krishna Nagar", area: "V V Nagar", areaKey: "Yousufguda", category: "Address", subtitle: "V V Nagar, Hyderabad", tags: ["krishna nagar", "road no 1"] }),
  place({ title: "Road No. 5, Ram Nagar", area: "L.B Nagar", areaKey: "LBnagar", category: "Address", subtitle: "L.B Nagar, Hyderabad", tags: ["ram nagar", "road no 5"] }),
  place({ title: "Madhura Nagar Colony", area: "Gachibowli", areaKey: "Gachibowli", category: "Address", subtitle: "Gachibowli, Hyderabad", tags: ["madhura nagar"] }),
  place({ title: "Road No. 12, Banjara Hills", area: "Banjara Hills", areaKey: "BanjaraHills", category: "Address", subtitle: "Banjara Hills, Hyderabad" }),
  place({ title: "Road No. 36, Jubilee Hills", area: "Jubilee Hills", areaKey: "JubileeHills", category: "Address", subtitle: "Jubilee Hills, Hyderabad" }),
  place({ title: "Raj Bhavan Road", area: "Somajiguda", areaKey: "Somajiguda", category: "Address", subtitle: "Somajiguda, Hyderabad" }),
  place({ title: "Minister Road", area: "Secunderabad", areaKey: "Secunderabad", category: "Address", subtitle: "Secunderabad, Hyderabad" }),
  place({ title: "SP Road", area: "Begumpet", areaKey: "Begumpet", category: "Address", subtitle: "Begumpet, Hyderabad" }),
  place({ title: "Outer Ring Road Gachibowli", area: "Gachibowli", areaKey: "Gachibowli", category: "Address", subtitle: "Gachibowli ORR, Hyderabad", tags: ["orr"] }),
  place({ title: "Airport Road", area: "Shamshabad", areaKey: "Shamshabad", category: "Address", subtitle: "Shamshabad, Hyderabad", tags: ["airport"] })
];

const ALL_PLACES = [
  ...TRANSIT_PLACES,
  ...METRO_STATIONS,
  ...AREA_PLACES,
  ...LANDMARKS,
  ...HOSPITALS,
  ...SHOPPING_AND_MARKETS,
  ...OFFICES_AND_CAMPUSES,
  ...HOTELS_TEMPLES_PARKS,
  ...RECENT_ADDRESS_PLACES,
  ...COMMON_ADDRESSES
];

const seenIds = new Set();
export const HYDERABAD_PLACES = ALL_PLACES.filter((item) => {
  if (seenIds.has(item.id)) return false;
  seenIds.add(item.id);
  return true;
});
